# Generated by Django 5.1 on 2024-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('user_id', models.CharField(max_length=255)),
                ('website_link', models.URLField()),
                ('address', models.TextField()),
                ('contract_title', models.CharField(max_length=255)),
                ('contract_description', models.TextField(blank=True, null=True)),
                ('contract_type', models.CharField(max_length=255)),
                ('custom_contract_type', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_months', models.PositiveIntegerField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('land_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=255)),
                ('crops', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('legal_clauses', models.JSONField(default=list)),
            ],
        ),
    ]
