# Generated by Django 5.1.2 on 2024-10-31 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('company_user_id', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('generative_id', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('tax_identification_number', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('number_of_contracts', models.PositiveIntegerField(blank=True, null=True)),
                ('company_type', models.CharField(max_length=100)),
                ('company_product', models.CharField(blank=True, max_length=100, null=True)),
                ('establish_date', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='company_profile_pics/')),
                ('achievements', models.JSONField()),
                ('additional_info', models.JSONField()),
                ('previous_contracts', models.JSONField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_designation', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website_link', models.URLField()),
                ('address', models.TextField()),
                ('contract_title', models.CharField(max_length=255)),
                ('contract_description', models.TextField(blank=True, null=True)),
                ('contract_type', models.CharField(max_length=255)),
                ('custom_contract_type', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_months', models.PositiveIntegerField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('land_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=255)),
                ('crops', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('legal_clauses', models.JSONField(default=list)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='contracts/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('farmer_user_id', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('contracts_made', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='farmer_profile_pics/')),
                ('farm_address', models.TextField()),
                ('land_area', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
                ('custom_soil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('farm_type', models.CharField(max_length=50)),
                ('well', models.BooleanField(null=True)),
                ('preferred_crops', models.JSONField(default=list)),
                ('achievements', models.JSONField(default=list)),
                ('additional_info', models.JSONField(default=list)),
                ('contracts', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
