# Generated by Django 5.1.2 on 2024-11-01 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_title', models.CharField(max_length=255)),
                ('contract_description', models.TextField(blank=True, null=True)),
                ('contract_type', models.CharField(max_length=255)),
                ('custom_contract_type', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_months', models.PositiveIntegerField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('land_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=255)),
                ('crops', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('legal_clauses', models.JSONField(default=list)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='contracts/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
