# Generated by Django 5.1 on 2024-10-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generative_id', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('tax_identification_number', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('number_of_contracts', models.PositiveIntegerField(blank=True, null=True)),
                ('company_type', models.CharField(max_length=100)),
                ('company_product', models.CharField(blank=True, max_length=100, null=True)),
                ('establish_date', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('achievements', models.JSONField()),
                ('additional_info', models.JSONField()),
                ('previous_contracts', models.JSONField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_designation', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('contracts_made', models.PositiveIntegerField()),
                ('profile_pic', models.URLField(null=True)),
                ('farm_address', models.TextField()),
                ('land_area', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
                ('farm_type', models.CharField(max_length=50)),
                ('well', models.BooleanField()),
                ('preferred_crops', models.JSONField()),
                ('land_pictures', models.JSONField()),
                ('achievements', models.JSONField()),
                ('additional_info', models.JSONField()),
                ('contracts', models.JSONField()),
            ],
        ),
    ]
