# Generated by Django 5.1 on 2024-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyprofile_farmerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
