# Generated by Django 5.1.2 on 2024-10-31 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contract_type', models.CharField(max_length=100)),
                ('custom_contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_months', models.IntegerField()),
                ('conditions', models.TextField()),
                ('start_date', models.DateField()),
                ('land_required', models.FloatField()),
                ('payment_type', models.CharField(max_length=100)),
                ('crops', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('legal_clauses', models.JSONField(default=list)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='contract_crop_images/')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company_user')),
            ],
        ),
    ]
