# Generated by Django 5.1.2 on 2024-11-12 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Initiated', max_length=20)),
                ('sub_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Production Stage', 'Production Stage'), ('Harvest and Collection Stage', 'Harvest and Collection Stage'), ('Payment', 'Payment'), ('Completed', 'Completed')], default='Initiated', max_length=30)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contract')),
                ('contract_post_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_contracts', to=settings.AUTH_USER_MODEL)),
                ('deal_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
