# Generated by Django 5.1.2 on 2024-10-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
