# Generated by Django 4.0.1 on 2024-10-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profilepic_remove_farmerprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='land_pictures',
        ),
    ]
