# Generated by Django 5.1.2 on 2024-11-12 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contractmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmanagement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contract', unique=True),
        ),
    ]
