# Generated by Django 4.0.1 on 2024-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_farmerprofile_land_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='achievements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='additional_info',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='contracts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='preferred_crops',
            field=models.JSONField(default=list),
        ),
    ]
