# Generated by Django 4.0.1 on 2024-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_farmerprofile_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='well',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='custom_soil_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='contracts_made',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
