# Generated by Django 4.0.1 on 2024-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_farmerprofile_well_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
