# Generated by Django 4.0.1 on 2024-10-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_farmerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='farmer_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to='api.farmerprofile'),
        ),
    ]
