# Generated by Django 4.0.1 on 2024-10-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profilepic_farmer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
