# Generated by Django 4.0.1 on 2024-10-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_farmerprofile_image_alter_farmerprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
