# Generated by Django 4.0.1 on 2024-10-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_contract_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_profile_pics/'),
        ),
    ]
