# Generated by Django 5.1.2 on 2024-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_companyprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
