# Generated by Django 5.1.2 on 2024-10-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_companyprofile_email_companyprofile_name_and_more'),
    ]

    operations = [
    ]
