# Generated by Django 5.1.2 on 2024-10-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20241030_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='well',
            field=models.BooleanField(null=True),
        ),
    ]
